FROM node:20-alpine

WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./
RUN yarn install --immutable

COPY . .

ENV NODE_ENV=production

USER node
EXPOSE 3000

CMD ["yarn", "tsx", "src/app.ts"]
